/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "sticks": "树枝",
    "Practice": "练习",
    "Your sticks has a boost of ×": "你的树枝有一个提升 x",
    "Crafting": "制作",
    "Experience boosts Experience.": "经验提升经验。",
    "Trial and Error": "试错法",
    "Sticks boost experience.": "树枝提升经验。",
    "ACH": "成就",
    "Chop": "砍树",
    "Chopper": "斩波器",
    "Click to chop a tree which would grant you wood.": "点击砍树，可以获得木头。",
    "Gain 1 more wood per click": "每次点击增加1块木头",
    "Unlock 2 more stick upgrades": "再解锁2个树枝升级",
    "UpGs": "升级",
    "wood": "木头",
    "Your wood has a boost of ×": "你的木头有一个提升 x",
    "research": "研究",
    "Inventing Fire": "发明火",
    "Study and get 1 research": "学习，得到 1 研究",
    "Unlock more wood upgrades, and get the ability to hold wood clickable.": "解锁更多木头升级，并获得长按木头点击的能力。",
    "Study - 25 Sticks": "学习 - 25 树枝",
    "stone?": "石头?",
    "stop chopping": "停止砍树",
    "buy 1 seed": "购买 1 种子",
    "1 big step": "一大步",
    "maxed": "上限",
    "a lillion": "一百万",
    "a whole bunch": "一大堆",
    "above average": "中等偏上",
    "acquire 1 tin": "获得1锡",
    "acquire fire stage 1": "获得火阶段1",
    "acquire fire stage 2": "获得二级火力",
    "aleph / 0.1": "Aleph / 0.1",
    "aleph / 100,000": "Aleph / 100000",
    "another world": "另一个世界",
    "at the speed of exp": "以经验的速度",
    "attract.": "吸引。",
    "batterying": "电池",
    "burger khalifa": "汉堡哈利法",
    "buy all row 1 copper upgrades": "购买所有1排铜升级",
    "buy the 'Imported' upgrade": "购买“导入”升级",
    "buy the speedrun buyable": "买速跑可买的",
    "buy the x-pansion upgrade": "购买x-扩展升级",
    "complete broken sticks challenge": "完成打断树枝挑战",
    "complete the first test": "完成第一个测试",
    "complete tree root challenge": "完成树根挑战",
    "count 100,000 leaves": "数100,000片叶子",
    "count leaves": "数叶子",
    "dollar stores sells wood now": "一元店现在卖木头",
    "dont step": "不要迈步",
    "exit the planet": "离开地球",
    "expand": "扩张",
    "feel the thunder": "感受雷声",
    "futuristic sticks": "未来树枝",
    "galaxy delivery": "银河快递",
    "get 1 fire point": "获得1个火点",
    "get 1 leaf": "得到1片叶子",
    "get 1 refined wood": "获得1块精制木头",
    "get 10 refined wood": "获得10个精制木头",
    "get 100,000 mini sticks": "获得10万个迷你树枝",
    "get 1000 ethereal sticks": "获得1000根空灵树枝",
    "get 1000 experience": "获得1000经验",
    "get 100K sticks": "得到100 k树枝",
    "get 10M experience during the Ineffective Learning battery challenge": "在无效学习电池挑战中获得10M经验",
    "get 1e10 wood": "得到1e10的木头",
    "get 1M experience": "获得1M经验",
    "get 1M mini experience": "得到1 m迷你经验",
    "get 1M refined wood": "获得1M精炼木头",
    "get 2 mini points": "获得2迷你积分",
    "get 2 tin": "得到2锡",
    "get 250 cash": "获得250现金",
    "get 2e8 antimatter reward: unlock an antimatter upgrade": "获得2e8反物质奖励：解锁反物质升级",
    "get 3 magnets": "获得3个磁铁",
    "get 5 boxes": "获得5个盒子",
    "get 6 fire stages": "获得6个火焰阶段",
    "get a coal": "得到一个煤",
    "get a million leaves": "得到无数的树叶",
    "get a monoium": "得到一份单子",
    "get a tier 2 stick upgrade": "获得第2层的树枝升级",
    "get a trillion (1e12) sticks": "获得1万亿（1e12）树枝",
    "get all row 2 tier 2 stick upgrades": "获得所有第2行第2层树枝升级",
    "get the 2 starting fire point upgrades reward: get a new recovery": "获得2个起始火点升级奖励：获得一个新的恢复",
    "have 1 power or more": "有一个或更多的能力",
    "have 10 difficult sticks": "有10个坚硬的树枝",
    "have 100,000+ cash": "拥有10万+现金",
    "have 1000 mini experience": "有1000个迷你经验",
    "have more than 500 power": "拥有超过500的功率",
    "have your tree be 50 centimeters tall": "你的树有50厘米高吗",
    "have your tree be taller than 100,000 centimeters": "你的树高过10万厘米吗",
    "hire 1 researcher": "雇佣1名研究员",
    "hire 1,000 researchers": "雇佣1000名研究人员",
    "impossible": "不可能的",
    "indesicive": "犹豫不决",
    "isitreal?": "是真的吗？",
    "it's lit": "它很亮",
    "it's very convenient": "它很方便",
    "its easy": "这很简单",
    "its hard": "这很难",
    "its the same": "都是一样的",
    "little versions": "小版本",
    "make your tree be bigger than 1M centimeters": "让你的树大于1米厘米",
    "man behind everything": "一切背后的人",
    "max every upgrade from the mini upgrade tree up until row 4": "从迷你升级树到第4行，每个升级都是最大值",
    "max inconvenient challenge": "最不方便的挑战",
    "max out content": "最大化内容",
    "max the opposite challenge": "最大化相反的挑战",
    "maybe way too effective": "也许太有效了",
    "mind paying taxes": "注意纳税",
    "mini... skilled": "迷你……熟练的",
    "minimum wage": "最低工资",
    "moneh moneh moneh": "钱，钱，钱",
    "nano experience nano-nanotubes": "纳米体验纳米纳米管",
    "nanotubes": "纳米管",
    "no salary": "没有薪水",
    "not so broken": "没有那么破碎",
    "not the same": "不一样",
    "please step": "请一步",
    "rank #1": "排名# 1",
    "re-re-re-refined": "再-再-精炼",
    "REALLY effective": "真正有效",
    "reepeeteetive": "reepeeteetive",
    "reset for a difficult stick": "重设困难杆",
    "riches to rags": "从富到穷",
    "root of the problem": "问题的根源",
    "secret ingredient": "秘密配方",
    "skilled": "熟练的",
    "small but big": "小,但大",
    "stick lines": "树枝线",
    "stickocalypse": "粘滞天启",
    "sticks > humans": "树枝 > 人类",
    "stonks": "猛烈炮击",
    "successfully dumb": "成功的哑巴",
    "the choice": "选择",
    "the great wall of cap": "长城的帽子",
    "the megawatt": "兆瓦",
    "the opposite of what?": "与什么相反？",
    "too expensive": "太贵了",
    "TooEz": "图兹",
    "unlock statuses": "解锁动态",
    "unpaid people": "无薪人员",
    "upgrades? it's all yours, my friend.": "升级？都是你的了，我的朋友。",
    "upperclassman": "学长",
    "what is it": "这是什么？",
    "where's the reward": "奖励在哪里？",
    "whoops": "哎呀！",
    "wildfire": "野火",
    "willionare": "百万富翁",
    "yeowch": "耶！",
    "zoooooooooom": "呜呜呜呜",
    "Boost sticks depending on experience": "根据经验来提升树枝",
    "Experienced Sticks": "经验丰富的树枝",
    "Technology Break-out": "技术突破",
    "Unlock achievements and the tech tree": "解锁成就和科技树",
    "Unlocks Wood layer, and experience gain is added by 3.": "解锁木头层，经验值增加3。",
    "Wood Cutting": "木材切割",
    "+2 Wood per chop and unlock more wood upgrades": "每次砍+2块木头，解锁更多的木头升级",
    "Stick upgrades don't reset": "树枝升级不会重置",
    "Sticks are useful!!!": "树枝是有用的！！",
    "stone": "石头",
    "Stone Age": "石器时代",
    "Stone Axe": "石斧",
    "Stone boosts experience": "石头提升经验值",
    "Stone boosts sticks": "石头提升树枝",
    "Stone Tools": "石器",
    "Tin Cans": "锡罐",
    "Unlock even more stick upgrades": "解锁更多的树枝升级",
    "Unlock even more wood upgrades": "解锁更多的木头升级",
    "Unlock more stick upgrades": "解锁更多树枝升级",
    "Unlock researchers": "解锁研究人员",
    "Unlock the stone layer": "解锁石头层",
    "Unlock the tin layer": "解锁锡层",
    "Unlock the tree layer": "解锁树层",
    "Wood Expansion": "木头膨胀",
    "Experience, now from wood!": "经验，现在来自木头！",
    "High Quality Crafting": "高品质工艺",
    "Not ENOUGH STICKS!": "没有足够的树枝！",
    "Wood now boosts experience (Softcap 5x)": "木头现在提升经验（软上限 5x）",
    "Apply Fertilizer - 100 research": "施用肥料 - 100研究",
    "Artificial Wood Growth": "人造木头生长",
    "Books of Knowledge": "知识之书",
    "Boost Stone Wood effect to the power of 1.2": "将石木效果提升到力量 1.2",
    "Branches": "分支",
    "Convert 2500 sticks, 1000 wood into 1.00 stone sticks": "将2500树枝，1000木头转化为 1.00 石棒",
    "Double growth": "双倍生长",
    "Faster Growth": "更快的生长",
    "Fertilize the tree and get +0.0001 more centimeters per tick": "给树施肥，每一秒增加 0.0001 厘米",
    "Fertilizers": "化肥",
    "Hydroponic": "水培",
    "Larger Trees": "更大的树",
    "leaves": "树叶",
    "Leaves boost sticks and tech tree and achievements stay.": "树叶提升树枝、科技树和成就都保留了下来。",
    "Leaves boost wood": "树叶提升木头",
    "Let's research leaves?": "我们来研究树叶吧？",
    "Merge": "合并",
    "NEW and IMPROVED": "更新和改进",
    "researchers": "研究人员",
    "Researchers boost leaves": "研究人员提升树叶",
    "Sticking Sticks": "粘贴树枝",
    "Sticks boost itself": "树枝自我提升",
    "Stone boosts wood": "石头提升木头",
    "Stone Sticks": "石棒",
    "Stone Wood": "石木",
    "Tree Centimeters boost wood": "树厘米提升木头",
    "Unlock fertilizers and double growth": "解锁肥料和加倍增长",
    "Unlock more stick upgrades and unlock stone sticks": "解锁更多树枝升级和解锁石棒",
    "Unlock Refined Wood type": "解锁精制木头类型",
    "Unlock the leaves layer and boost experience by x2": "解锁树叶层并提升经验 x2",
    "Upgrades": "升级",
    "Wood boost itself": "木头自我提升",
    "Wood from Leaves!?!?": "树叶做成的木头！？！？",
    "Your leaves has a boost of ×": "你的叶子提升了 ×",
    "Your researchers has a boost of ×": "你的研究人员提升了 x",
    "Convert": "转换",
    "Convert 1000 wood into 1.00 refined wood (buys max)": "将 1000 木头转换成 1.00 精制木头（购买最大）",
    "Successfully Failed": "成功失败",
    "Artifical Wood": "神木",
    "Double research gain from researchers and unlock more wood upgrades": "从研究人员获得双倍的研究成果，并解锁更多的木材升级",
    "Re-searching": "研究",
    "Wood upgrades don't reset": "木头升级不会重置",
    "Serious Work": "认真的工作",
    "Researchers boost wood": "研究员提升木头",
    "Dont leaf me...": "别离开(leaf)我…",
    "Double leaf gain": "双倍树叶增益",
    "Even MORE EXPERIENCE": "更多的经验",
    "Passively generate 1% of sticks": "被动生成1%的树枝",
    "Reproducing Sticks": "复刻树枝",
    "Discover the BIG BANG": "发现大爆炸",
    "Passively gain 10% of sticks, Researchers boost itself and unlock more leaf upgrades": "被动地获得10%的重置所有进度并重新开始。此操作不能撤消。，研究员提升自己并解锁更多的叶子升级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "EXC Discord": "挖掘树 Discord",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "ST": "石头",
    "TR": "树",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': '树叶',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': '研究',
    'S': '树枝',
    'T': '科技',
    'U': 'U',
    'V': 'V',
    'W': '木头',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Boost Sticks by x": "提升树枝 x",
    "Boost Crafting effect to the power of ": "将制造效果提升至力量 ",
    "Boost trial and error effect to the power of ": "将试错效果提升至力量 ",
    "Boost Expierence, now from wood! Effect to the power of ": "提升经验，现在从木材！效果力量是 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\(([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\{(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have made a total of (.+) stone$/, '你总共制作了 $1 石头'],
    [/^Your tree is (.+) centimeters tall, and it is growing (.+) centimeters per tick.$/, '你的树高 $1 厘米，每tick生长 $2 厘米。'],
    [/^Your researchers are making (.+) research per tick, where each researcher makes (.+) research.$/, '你的研究人员每分钟进行 $1 研究，而每个研究人员进行 $2 研究。'],
    [/^You have (.+) refined wood$/, '你有 $1 精制木头'],
    [/^You have (.+) stone sticks$/, '你有 $1 石棒'],
    [/^You have (.+) leaves$/, '你有 $1 树叶'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) experience$/, '你有 $1 经验值'],
    [/^Next at (.+) leaves$/, '下一个在 $1 树叶'],
    [/^Next at (.+) refined wood$/, '下一个在 $1 精制木头'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Next at (.+) experience$/, '下一个在 $1 经验值'],
    [/^Gain (.+) experience per second.$/, '每秒获得 $1 点经验值。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) sticks$/, '$1e$2 树枝'],
    [/^([\d\.]+)e([\d\.,]+) experience$/, '$1e$2 经验值'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) sticks$/, '$1 树枝'],
    [/^([\d\.,]+) wood$/, '$1 木头'],
    [/^([\d\.,]+) research$/, '$1 研究'],
    [/^([\d\.,]+) stone$/, '$1 石头'],
    [/^([\d\.,]+) centimeters$/, '$1 厘米'],
    [/^([\d\.,]+) researchers$/, '$1 研究人员'],
    [/^([\d\.,]+) leaves$/, '$1 树叶'],
    [/^([\d\.,]+) Total Stone$/, '总计 $1 石头'],
    [/^x([\d\.,]+) wood$/, 'x$1 木头'],
    [/^Tier ([\d\.,]+)$/, '层 $1'],
    [/^get ([\d\.,]+) mini leaf$/, '获得 $1 迷你树叶'],
    [/^get ([\d\.,]+) mini point$/, '获得 $1 迷你积分'],
    [/^get ([\d\.,]+) mini stone$/, '获得 $1 迷你石头'],
    [/^get ([\d\.,]+) stone$/, '获得 $1 石头'],
    [/^get ([\d\.,]+) sticks$/, '获得 $1 树枝'],
    [/^get ([\d\.,]+) wood$/, '获得 $1 木头'],
    [/^get ([\d\.,]+) power$/, '获得 $1 力量'],
    [/^get rank ([\d\.,]+)$/, '获得 等级 $1'],
    [/^get tier ([\d\.,]+)$/, '获得 层级 $1'],
    [/^have ([\d\.,]+) power$/, '拥有 $1 力量'],
    [/^have ([\d\.,]+) mini researcher$/, '拥有 $1 迷你研究员'],
    [/^get ([\d\.]+)e([\d\.,]+) sticks$/, '获得 $1e$2 树枝'],
    [/^have ([\d\.]+)e([\d\.,]+) wood$/, '拥有 $1e$2 木头'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) sticks, (.+) stone sticks, (.+) tree centimeters$/, '成本：$1 树枝，$2 石棒，$3 树厘米'],
    [/^Cost: (.+) Wood, (.+) refined wood$/, '成本：$1 木头，$2 精制木头'],
    [/^Cost: (.+) researchers$/, '成本：$1 研究员'],
    [/^Cost: (.+) wood$/, '成本：$1 木头'],
    [/^Cost: (.+) research$/, '成本：$1 研究'],
    [/^Cost: (.+) sticks$/, '成本：$1 树枝'],
    [/^Cost: (.+) leaves$/, '成本：$1 树叶'],
    [/^Cost: (.+) centimeters$/, '成本：$1 厘米'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) stone$/, '成本：$1 石头'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) sticks$/, '要求：$1 树枝'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);